[INFO              ] Logger: Record log in /mnt/sdcard/kivy/new/.kivy/logs/kivy_16-11-28_2.txt
[INFO              ] Kivy: v1.9.1
[INFO              ] Python: v2.7.2 (default, Mar 20 2016, 23:30:13) 
[GCC 4.8]
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "main.py", line 13, in <module>
[WARNING           ] stderr:     from kivy.garden.mapview import MapView, MapMarker, MapSource, MarkerMapLayer, MapMarkerPopup,GeoJsonMapLayer
[WARNING           ] stderr:   File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/garden/__init__.py", line 100, in load_module
[WARNING           ] stderr:   File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/garden/__init__.py", line 104, in _load_module
[WARNING           ] stderr:   File "/mnt/sdcard/kivy/new/.kivy/garden/garden.mapview/__init__.py", line 3, in <module>
[WARNING           ] stderr:     from .mapview import *
[WARNING           ] stderr:   File "/mnt/sdcard/kivy/new/.kivy/garden/garden.mapview/mapview/__init__.py", line 30, in <module>
[WARNING           ] stderr:     from mapview.source import MapSource
[WARNING           ] stderr:   File "/mnt/sdcard/kivy/new/.kivy/garden/garden.mapview/mapview/source.py", line 8, in <module>
[WARNING           ] stderr:     from mapview.downloader import Downloader
[WARNING           ] stderr:   File "/mnt/sdcard/kivy/new/.kivy/garden/garden.mapview/mapview/downloader.py", line 8, in <module>
[WARNING           ] stderr:     from concurrent.futures import ThreadPoolExecutor, TimeoutError, as_completed
[WARNING           ] stderr: ImportError: No module named concurrent.futures
